language: php

matrix:
  include:
    - php: 7.2
      env: VERS="8.5.8"
    - php: 7.3
      env: VERS="9.3.11"
    - php: 7.4
      env: VERS="9.3.11"
    - php: nightly
      env: VERS="9.3.11"
  fast_finish: true
  allow_failures:
    - php: nightly

install:
  - composer install
  - if [[ $VERS == "8.5.8" ]]; then composer require "phpunit/phpunit:8.5"; fi
  - if [[ $VERS == "9.3.11" ]]; then composer require "phpunit/phpunit:9.3"; fi

script:
  - vendor/bin/phpunit