dist: xenial
language: php

jobs:
  fast_finish: true
  include:
    - php: 7.3
    - install: composer require phpunit/phpunit "^9.3"
    - script: vendor/bin/phpunit

cache:
 directories:
   - $HOME/.composer/cache/files