language: php

matrix:
  include:
    - php: 7.2
      env: VERS="8.4"
    - php: 7.3
      env: VERS="9.3"
    - php: 7.4
      env: VERS="9.3"
    - php: nightly
      env: VERS="9.3"
  fast_finish: true
  allow_failures:
    - php: nightly

install:
  - composer require "phpunit/phpunit:${VERS}"

script:
  - vendor/bin/phpunit