language: php

matrix:
  include:
    - php: 7.2
      env: VERS="8.5.8"
    - php: 7.3
      env: VERS="9.3.11"
    - php: 7.4
      env: VERS="9.3.11"
    - php: nightly
      env: VERS="9.3.11"
  fast_finish: true
  allow_failures:
    - php: nightly

before_install:
  - composer require "phpunit/phpunit:$VERS

install:
  - composer install

script:
  - vendor/bin/phpunit