language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

before_install:
  - composer self-update
  - composer install --no-interaction --dev

script:
  - phpunit

cache:
 directories:
   - $HOME/.composer/cache/files