language: php

php:
  - 7.3
  - 7.4
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

before_install:
  - composer self-update
  - composer require phpunit/phpunit

script:
  - vendor/bin/phpunit