dist: xenial
language: php

_shared_job: &shared_job
  script: vendor/bin/phpunit
jobs:
  fast_finish: true
  include:
    - php: 7.0
      install: composer require phpunit/phpunit "6.5.14"
      <<: *shared_job
    - php: 7.1
      install: composer require phpunit/phpunit "7.5.20"
      <<: *shared_job
    - php: 7.2
      install: composer require phpunit/phpunit "8.5.8"
      <<: *shared_job
    - php: 7.3
      install: composer require phpunit/phpunit "^9.3"
      <<: *shared_job
    - php: 7.4
      install: composer require phpunit/phpunit "^9.3"
      <<: *shared_job

cache:
 directories:
   - $HOME/.composer/cache/files